### ISSUE TITLE
Subcommand support

### ISSUE THREAD

**Issue by arendsee** [trevorld/argparse#14]
It would be neat if argparse supported subcommands.

For example,
``` R
parser <- ArgumentParser()
subparser <- parser$add_subparsers()
foo_parser <- subparser$add_parser('foo', help="foo subcommand")
bar_parser <- subparser$add_parser('bar', help="bar subcommand")
foo_parser$add_argument('x', help="foo's x")
bar_parser$add_argument('x', help="bar's x")
```

The subcommand structure is really powerful for large command line programs (e.g. git) and is pretty easy to use in python's argparse.

**Comment by trevorld** [comment]
Subcommand support would be pretty cool however seems kind of complicated to implement.  Adding this will be a low priority for me.

**Comment by trevorld** [comment]
Should do #25 before this.
