### ISSUE TITLE
Use of the argparse 'required' argument causes default arguments to be required

### ISSUE THREAD

**Issue by clairemcwhite** [trevorld/argparse#17]
This happens whether you set required as FALSE or TRUE. 

Works fine
```{r}
parser <- ArgumentParser()
parser$add_argument("-o", "--output_filename", action="store",
                        dest="output_filename", help="Output filename for resulting plot", default="outfile.txt")
args <- parser$parse_args()
print(args$output_filename)
```
[1] "outfile.txt"

Gives error
```{r}
parser <- ArgumentParser()
parser$add_argument("-o", "--output_filename", action="store", required=FALSE,
                        dest="output_filename", help="Output filename for resulting plot", default="outfile.txt")
args <- parser$parse_args()
print(args$output_filename)
```
error: argument -o/--output_filename is required

**Comment by trevorld** [comment]
Thanks for the bug report!  Should be fixed now in the developmental version.

**Comment by chinnarii** [comment]
from PIL import Image
import pytesseract
import argparse
import cv2

# construct the argument parser and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", required=True, help="C:/Users/admin/Desktop/Images/Image1.png")
args = vars(ap.parse_args())

# load the image and convert it to grayscale
image = cv2.imread(args["image"])
cv2.imshow("Original", image)

# Apply an "average" blur to the image

blurred = cv2.blur(image, (3,3))
cv2.imshow("Blurred_image", blurred)
img = Image.fromarray(blurred)
text = pytesseract.image_to_string(img, lang='eng')
print (text)
cv2.waitKey(0)

getting below error
error: argument -i/--image is required

please help

**Comment by trevorld** [comment]
@chinnarii Your comment has been removed because not only is it off-topic of this particular issue it is related to a completely different programming language (python) and is hence off-topic to this R package.
