### ISSUE TITLE
Feature request: mutally exclusive

### ISSUE THREAD

**Issue by vreuter** [trevorld/argparse#23]
Inclusion of the `add_mutually_exclusive_group` functionality of the python version would be awesome if possible.

**Comment by trevorld** [comment]
``add_mutually_exclusive_group`` functionality would be awesome but like #14 seems like it would be tricky to implement.  Adding this will be a low priority for me.

**Comment by vreuter** [comment]
OK! Yeah while it'd be nice, it's certainly easy enough generally to do a little post-hoc validation after the parse.

**Comment by trevorld** [comment]
Should implement #25 before this.
