### ISSUE TITLE
Support add_argument_group

### ISSUE THREAD

**Issue by dariober** [trevorld/argparse#26]
Hi- Is it possible to use or implement the `add_argument_group` as described in  https://docs.python.org/3/library/argparse.html#argument-groups

Like:

```
parser<- ArgumentParser()
group1<- parser$add_argument_group('Group 1')
...
```

(I guess this falls in the same category as #14 and #23 but I'll try asking anyway...) 

Thank you!

**Comment by trevorld** [comment]
Should implement #25 before this.
