### ISSUE TITLE
print help, print usage, return code and stderr redirection

### ISSUE THREAD

**Issue by PlasmaBinturong** [trevorld/argparse#8]
Hi,

regarding the default print_help action and print_usage (when an command-line error is encountered), the R package doesn't behave like the python argparse:

- if I call my script with "-h"/"--help" option, the return code is 1 ; which is not expected since it's not an error (?)
- when doing an error, for example omitting an argument, the print_usage prints to stdout... (whereas in python argparse it prints to stderr, as I would expect)

All minor stuff but surprising when trying to catch and redirect errors.
Thanks !

**Comment by trevorld** [comment]
Good catches.  I'll look into it in the next few weeks.

Thanks!
